
version: '3'

services:

  gunicorn:
      build: .
      container_name: 'gunicorn'
      restart: always
      command: /bin/sh -c "python3 -m gunicorn -b 0.0.0.0:80 mlflow_employee.wsgi --reload"
      volumes:
        - .:/app
      ports:
        - 80:80
      environment:
        - DJANGO_SUPERUSER_USERNAME=admin
        - DJANGO_SUPERUSER_PASSWORD=admin
        - DJANGO_SUPERUSER_EMAIL=admin@example.com

  mlflow-server:
    build:
      dockerfile: ./MLFlowServer.dockerfile
    volumes:
      - ./MLFlowRegistry:/MLFlowRegistry
    working_dir: /
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /MLFlowRegistry/artifacts --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"

    healthcheck:
      test: [ "CMD", "echo" ]
      interval: 10s
      timeout: 5s
      retries: 5